{"name": "test_mul_004", "status": "failed", "statusDetails": {"message": "AssertionError: assert False", "trace": "self = <test_file_005.Test_Credence_005 object at 0x0000017BE8B06290>\n\n    def test_mul_004(self):\n        a = 3\n        b = 7\n        mul = a * b\n        print(\"Mul of a and b is :\" + str(mul))\n        if mul == 10:\n            assert True\n        else:\n>           assert False\nE           assert False\n\ntest_file_005.py:11: AssertionError"}, "attachments": [{"name": "stdout", "source": "40763bdd-aeb9-4a43-98b7-020cdb6039e0-attachment.txt", "type": "text/plain"}], "start": 1690958994051, "stop": 1690958994052, "uuid": "01ebd384-e083-4b5a-bbf5-9bc0102001fa", "historyId": "3373f973f87d181b033c1208fbde30ae", "testCaseId": "3373f973f87d181b033c1208fbde30ae", "fullName": "test_file_005.Test_Credence_005#test_mul_004", "labels": [{"name": "suite", "value": "test_file_005"}, {"name": "subSuite", "value": "Test_Credence_005"}, {"name": "host", "value": "VARSHA"}, {"name": "thread", "value": "1100-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_file_005"}]}