{"name": "test_mul_004", "status": "failed", "statusDetails": {"message": "AssertionError: assert False", "trace": "self = <test_file_003.Test_Credence_003 object at 0x0000017BE8B04950>\n\n    def test_mul_004(self):\n        a = 3\n        b = 7\n        mul = a * b\n        print(\"Mul of a and b is :\" + str(mul))\n        if mul == 10:\n            assert True\n        else:\n>           assert False\nE           assert False\n\ntest_file_003.py:11: AssertionError"}, "attachments": [{"name": "stdout", "source": "637cbce7-be88-4140-b3d5-33173d1f7dd7-attachment.txt", "type": "text/plain"}], "start": 1690958993866, "stop": 1690958993866, "uuid": "706d56e6-329a-4887-85ec-29f05f343e45", "historyId": "1da0023011657c42a38b1de108e70725", "testCaseId": "1da0023011657c42a38b1de108e70725", "fullName": "test_file_003.Test_Credence_003#test_mul_004", "labels": [{"name": "suite", "value": "test_file_003"}, {"name": "subSuite", "value": "Test_Credence_003"}, {"name": "host", "value": "VARSHA"}, {"name": "thread", "value": "1100-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_file_003"}]}